# Preprocessing Data Teks untuk Analisis Toxicity

Notebook ini berfokus pada tahap preprocessing data teks sebelum dilakukan pelatihan model. Tujuan utama dari proses ini adalah:
- membersihkan data yang tidak relevan atau tidak valid,
- mengurangi noise dan duplikat,
- menstandardisasi bentuk teks agar lebih konsisten,
- menyiapkan fitur teks yang siap dipakai oleh model pada tahap selanjutnya.

Pada bagian berikut, setiap sub-bagian menjelaskan alasan dan hasil dari proses preprocessing yang dilakukan secara berurutan.

In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/indotoxic2024_annotated_data-3.csv")

In [2]:
# hapus spam
df = df[df["is_noise_or_spam_text"] == 0].copy()

# hapus teks yang kosong
empty_mask = (
    df["text"].isna() |
    df["text"].astype(str).str.strip().eq("")
)
df = df[~empty_mask].copy()

### 1. Duplicate Handling

Tujuan bagian ini adalah menghilangkan data yang berulang atau tidak konsisten agar model tidak belajar dari contoh yang sama berulang kali. Proses yang dilakukan meliputi:
- mendeteksi teks duplikat berdasarkan isi teks,
- menyimpan teks yang memiliki label konflik untuk dokumentasi,
- menghapus text yang menimbulkan ambiguitas label,
- menjaga satu representasi terbaik untuk setiap teks unik.

In [3]:
# Mengambil teks duplikat
duplicate_mask = df.duplicated(
    subset=["text"],
    keep=False
)

duplicates = df[duplicate_mask].copy()

# Mengambil teks yang memiliki label konflik
label_conflict = (
    df.groupby("text")["toxicity"]
      .nunique()
      .reset_index(name="n_label")
)

conflict_texts = label_conflict[
    label_conflict["n_label"] > 1
]["text"]

# simpan konflik ke file CSV utk dokumentasi
df_conflict = df[
    df["text"].isin(conflict_texts)
].copy()

df_conflict.to_csv(
    "../data/interim/label_conflict.csv",
    index=False
)

# hapus teks yang memiliki label konflik
df = df[
    ~df["text"].isin(conflict_texts)
].copy()

df = df.drop_duplicates(
    subset=["text"],
    keep="first"
).copy()

In [4]:
print("Shape akhir setelah cleaning:")
print(df.shape)

print("\nDuplicate text:")
print(df["text"].duplicated().sum())

Shape akhir setelah cleaning:
(23009, 17)

Duplicate text:
0

### 2. Ekstraksi Emoji

Bagian ini bertujuan untuk menangkap informasi tambahan dari teks yang sering mengandung ekspresi seperti emoji. Emoji dapat merepresentasikan emosi atau tone komentar, sehingga ekstraksi ini berguna untuk menjaga konteks semantik yang mungkin hilang saat teks dibersihkan. Hasil ekstraksi disimpan di kolom emoji untuk dipelajari lebih lanjut atau dianalisis sebagai fitur pendukung.

In [5]:
import emoji

def extract_emojis(text):
    return " ".join(
        item["emoji"]
        for item in emoji.emoji_list(str(text))
    )

df["emoji"] = df["text"].apply(extract_emojis)

In [6]:
df["emoji"].unique()

array(['', '😔', '👍', ..., '🔥 👍 🤑 💯 👍 🤑 🔥 💯 🤑 🔥 👍 💯', '🏨 🏨 🎀 📩 📩', '🇨🇳 🇲🇾'],
      shape=(2231,), dtype=object)

### 3. Cleaning Text

Tujuan bagian ini adalah membersihkan teks dari karakter noise yang tidak relevan untuk analisis sentimen atau toxicitas. Beberapa proses yang dilakukan meliputi:
- lowercase agar format teks konsisten,
- menghapus emoji, URL, HTML, mention, dan hashtag,
- menghilangkan tanda baca dan karakter berulang,
- menyederhanakan spasi agar teks menjadi lebih rapi dan standar.

Output dari proses ini adalah kolom text_clean yang siap diproses lebih lanjut.

In [7]:
import re

df["text_clean"] = df["text"].copy()

def clean_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    
    # Lowercase
    text = text.lower()
    
    # Hapus emoji
    text = emoji.replace_emoji(text, replace="")
    
    # Hapus URL
    text = re.sub(r"http\S+|www\S+", " ", text)
    
    # Hapus HTML tag seperti <br>, <br><br>
    text = re.sub(r"<[^>]+>", " ", text)
    
    # Hapus mention
    text = re.sub(r"@\w+", " ", text)
    
    # Hapus hashtag symbol tetapi pertahankan katanya
    # #SavePalestine -> SavePalestine
    text = re.sub(r"#(\w+)", r"\1", text)
    
    # Hilangkan punctuation
    text = re.sub(r"[^\w\s]", " ", text)
    
    # Normalisasi repeated characters
    text = re.sub(r"(.)\1{2,}", r"\1", text)
    
    # Normalisasi whitespace
    text = re.sub(r"\s+", " ", text).strip()
    
    return text
df["text_clean"] = df["text"].apply(clean_text)

### 4. Slang Normalization

Bagian ini bertujuan untuk menormalkan bahasa informal atau singkatan yang umum dipakai di media sosial. Banyak komentar mengandung kata slang, singkatan, atau variasi ejaan yang berbeda, sehingga perlu dikonversi ke bentuk baku agar model dapat memahami maknanya dengan lebih konsisten. Proses ini meningkatkan kualitas representasi teks sebelum masuk ke tahap pemodelan.

In [8]:
slang_dict = {
    # Negasi
    "gak": "tidak", "ga": "tidak", "gk": "tidak", "nggak": "tidak",
    "ngga": "tidak", "kaga": "tidak", "kagak": "tidak", "tdk": "tidak",

    # Kata ganti & partikel umum
    "yg": "yang", "dgn": "dengan", "bgt": "banget", "aja": "saja",
    "sy": "saya", "gw": "saya", "gue": "saya", "gua": "saya",
    "lu": "kamu", "lo": "kamu", "elo": "kamu", "km": "kamu",
    "kmu": "kamu", "elu": "kamu", "w": "saya",

    # Kata tanya & keterangan
    "krn": "karena", "krna": "karena", "karna": "karena",
    "utk": "untuk", "buat": "untuk", "jd": "jadi", "jgn": "jangan",
    "jgnkan": "jangankan", "gmn": "bagaimana", "gimana": "bagaimana",
    "knp": "kenapa", "kenapa": "mengapa", "dmn": "dimana",
    "drmn": "dari mana", "kpn": "kapan", "brp": "berapa",
    "brapa": "berapa", "sm": "sama", "sma": "sama",

    # Waktu
    "skrg": "sekarang", "skrng": "sekarang", "td": "tadi",
    "bsk": "besok", "kmrn": "kemarin", "kmaren": "kemarin",
    "tar": "nanti", "ntar": "nanti", "nti": "nanti",

    # Kata kerja & sifat
    "udh": "sudah", "udah": "sudah", "dah": "sudah", "blm": "belum",
    "blum": "belum", "bkn": "bukan", "bnr": "benar", "bener": "benar",
    "emg": "memang", "emang": "memang", "tau": "tahu", "gatau": "tidak tahu",
    "gtau": "tidak tahu", "pgn": "ingin", "pengen": "ingin",
    "pngen": "ingin", "mau": "ingin", "bs": "bisa", "bsa": "bisa",
    "hrs": "harus", "harusnya": "seharusnya",

    # Kata sifat & ekspresi
    "bgt": "banget", "bngt": "banget", "bener2": "benar-benar",
    "cape": "capai", "capek": "lelah", "cakep": "cantik/tampan", 
    "kece": "keren", "mantul": "mantap betul", "mantep": "mantap",
    "gokil": "gila", "parah": "sangat", "anjay": "ekspresi kaget/kagum",
    "santuy": "santai", "woles": "santai", "baper": "bawa perasaan",
    "kepo": "ingin tahu urusan orang", "julid": "iri/sirik",
    "ambyar": "hancur/berantakan", "receh": "lucu remeh",

    # Singkatan chat umum
    "otw": "on the way / dalam perjalanan", "gpp": "tidak apa-apa",
    "gapapa": "tidak apa-apa", "cmiiw": "correct me if I'm wrong",
    "btw": "ngomong-ngomong", "fyi": "sebagai informasi",
    "pls": "tolong", "thx": "terima kasih", "makasih": "terima kasih",
    "gaje": "tidak jelas", "japri": "jalur pribadi (chat pribadi)",
    "japrii": "jalur pribadi", "wkwk": "tertawa", "wkwkwk": "tertawa",
    "haha": "tertawa", "anjir": "ekspresi kaget", "yaudah": "ya sudah",
    "udahlah": "sudahlah", "kayanya": "kayaknya", "kayaknya": "sepertinya",
    "kyk": "seperti", "kek": "seperti", "sbnrnya": "sebenarnya",
    "sebenarnya": "pada dasarnya", "org": "orang", "org2": "orang-orang",
    "tp": "tapi", "tpi": "tapi", "dr": "dari", "trs": "terus",
    "trus": "terus", "abis": "habis", "abisin": "habiskan",
    "duit": "uang", "cuan": "keuntungan/uang", "gaje": "tidak jelas",
}

In [9]:
def normalize_repeated_char(text):
    text = re.sub(r"(.)\1{2,}", r"\1", text)
    return text

def normalize_slang(text):
    words = text.split()
    
    normalized = [
        slang_dict.get(word, word)
        for word in words
    ]
    
    return " ".join(normalized)

df["text_clean"] = df["text_clean"].apply(normalize_repeated_char)
df["text_clean"] = df["text_clean"].apply(normalize_slang)

### 5. Topic Handling

Tujuan dari bagian ini adalah menyiapkan struktur data untuk kolom topic agar lebih mudah diproses dan divisualisasikan. Teks topic biasanya berbentuk string yang berisi beberapa kategori dengan pemisah koma, sehingga perlu diubah menjadi list agar lebih efektif untuk analisis lebih lanjut, seperti pemetaan tema atau eksplorasi label.

In [10]:
df["topic_list"] = (
    df["topic"]
    .fillna("")
    .apply(
        lambda x: [
            topic.strip()
            for topic in str(x).split(",")
            if topic.strip()
        ]
    )
)

In [11]:
df[["topic", "topic_list"]].head()

                     topic                 topic_list
0              Disabilitas              [Disabilitas]
1                   Jewish                   [Jewish]
2  Terpolarisasi, Tionghoa  [Terpolarisasi, Tionghoa]
3    Terpolarisasi, Jewish    [Terpolarisasi, Jewish]
6  Terpolarisasi, Tionghoa  [Terpolarisasi, Tionghoa]

### Stopword

In [12]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

stopword_factory = StopWordRemoverFactory()
stopwords = set(stopword_factory.get_stop_words())

In [13]:
def remove_stopwords(text, stopwords=stopwords):
    if pd.isna(text):
        return ""
    
    words = str(text).split()
    
    filtered_words = [
        word for word in words
        if word not in stopwords
    ]
    
    return " ".join(filtered_words)

### Stemming

In [14]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from sklearn.preprocessing import MultiLabelBinarizer

In [15]:
stemmer_factory = StemmerFactory()
stemmer = stemmer_factory.create_stemmer()

In [16]:
def stem_text(text):
    if pd.isna(text):
        return ""
    
    return stemmer.stem(str(text))

### Label Encoder

In [17]:
import pandas as pd

def normalize_topic_list(topic):
    if pd.isna(topic):
        return []
    
    if isinstance(topic, list):
        return [
            str(x).strip()
            for x in topic
            if str(x).strip()
        ]
    
    topic = str(topic).strip()
    
    if not topic:
        return []
    
    return [
        x.strip()
        for x in topic.split(",")
        if x.strip()
    ]

In [18]:
def encode_multilabel_column(data, column):
    """
    Mengubah kolom yang berisi list label menjadi multi-hot encoding.
    """
    
    mlb = MultiLabelBinarizer()
    
    encoded = mlb.fit_transform(data[column])
    
    encoded_df = pd.DataFrame(
        encoded,
        columns=[
            f"{column}_{label}"
            for label in mlb.classes_
        ],
        index=data.index
    )
    
    return encoded_df, mlb

In [22]:
import time
import pandas as pd
from tqdm.auto import tqdm

tqdm.pandas()


def re_preprocess(
    data,
    stopword_remove=True,
    encode_topic=False,
    stem=True
):
    
    df = data.copy()

    print("=" * 50)
    print("START PREPROCESSING")
    print(f"Jumlah data : {len(df):,}")
    print("=" * 50)

    # =========================
    # 1. Validasi
    # =========================
    if "text_clean" not in df.columns:
        raise ValueError(
            "Kolom 'text_clean' tidak ditemukan."
        )

    # =========================
    # 2. Stopword Removal
    # =========================
    if stopword_remove:

        print("\n[1/3] Stopword removal...")
        start = time.time()

        df["text_processed"] = df["text_clean"].progress_apply(
            remove_stopwords
        )

        elapsed = time.time() - start
        print(f"✓ Selesai: {elapsed:.2f} detik")

    else:

        print("\n[1/3] Stopword removal: SKIP")

        df["text_processed"] = df["text_clean"]

    # =========================
    # 3. Stemming
    # =========================
    if stem:

        print("\n[2/3] Stemming...")
        print("    Proses ini bisa memakan waktu cukup lama.")

        start = time.time()

        df["text_processed"] = df["text_processed"].progress_apply(
            stem_text
        )

        elapsed = time.time() - start
        print(f"✓ Selesai: {elapsed:.2f} detik")

    else:

        print("\n[2/3] Stemming: SKIP")

    # =========================
    # 4. Topic Encoding
    # =========================
    topic_encoder = None

    if encode_topic:

        print("\n[3/3] Topic encoding...")
        start = time.time()

        if "topic" not in df.columns:
            raise ValueError(
                "Kolom 'topic' tidak ditemukan."
            )

        df["topic_list"] = df["topic"].apply(
            normalize_topic_list
        )

        topic_encoded, topic_encoder = (
            encode_multilabel_column(
                df,
                "topic_list"
            )
        )

        df = pd.concat(
            [df, topic_encoded],
            axis=1
        )

        elapsed = time.time() - start
        print(f"✓ Selesai: {elapsed:.2f} detik")

    else:

        print("\n[3/3] Topic encoding: SKIP")

    print("\n" + "=" * 50)
    print("PREPROCESSING SELESAI")
    print("=" * 50)

    return df, topic_encoder

c:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [25]:
df_processed, topic_encoder = re_preprocess(
    df,
    stopword_remove=True,
    encode_topic=False,
    stem=True
)

==================================================
START PREPROCESSING
Jumlah data : 23,009
==================================================

[1/3] Stopword removal...

100%|██████████| 23009/23009 [00:00<00:00, 108495.13it/s]

✓ Selesai: 0.22 detik

[2/3] Stemming...
    Proses ini bisa memakan waktu cukup lama.

100%|██████████| 23009/23009 [1:31:32<00:00,  4.19it/s]

✓ Selesai: 5492.09 detik

[3/3] Topic encoding: SKIP

==================================================
PREPROCESSING SELESAI
==================================================

### 6. Cek Hasil Akhir

Bagian ini berfungsi sebagai validasi kualitas preprocessing. Tujuannya adalah memastikan tidak ada teks kosong yang tersisa setelah proses pembersihan dan bahwa data yang sudah dibersihkan siap digunakan pada tahapan berikutnya. Proses pengecekan ini penting agar hasil akhir konsisten dan meminimalkan error dalam pelatihan model.

In [26]:
empty_after_cleaning = (
    df["text_clean"].str.strip().eq("")
)

print(
    "Text kosong setelah cleaning:",
    empty_after_cleaning.sum()
)
df = df[~empty_after_cleaning].copy()

Text kosong setelah cleaning: 0

In [29]:
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23009 entries, 0 to 43678
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   batch_id                       23009 non-null  int64
 1   batch_text_id                  23009 non-null  int64
 2   text_id                        23009 non-null  object
 3   metadata_id                    23009 non-null  int64
 4   annotator_id                   23009 non-null  int64
 5   text                           23009 non-null  object
 6   initial_paragraph              1236 non-null   object
 7   topic                          23009 non-null  object
 8   is_noise_or_spam_text          23009 non-null  int64
 9   related_to_election_2024       23009 non-null  int64
 10  toxicity                       23009 non-null  int64
 11  profanity_obscenity            23009 non-null  int64
 12  threat_incitement_to_violence  23009 non-null  int64
 13  insults                        23009 non-null  int64
 14  identity_attack                23009 non-null  int64
 15  sexually_explicit              23009 non-null  int64
 16  category_count                 23009 non-null  int64
 17  emoji                          23009 non-null  object
 18  text_clean                     23009 non-null  object
 19  topic_list                     23009 non-null  object
 20  text_processed                 23009 non-null  object
dtypes: int64(13), object(8)
memory usage: 3.9+ MB

In [30]:
pd.set_option("display.max_colwidth", 200)

df_processed[
    ["text", "emoji", "text_clean", "topic_list", "text_processed"]
].sample(10)

,text,emoji,text_clean,topic_list,text_processed
5270,Wah gila sih intronya ganteng banget. Ngalah ngalahin boy group aespa Drama Intro #aespaDrama #Drama #aespa #에스파 @aespa_official,,wah gila sih intronya ganteng banget ngalah ngalahin boy group aespa drama intro aespadrama drama aespa 에스파,[Disabilitas],wah gila sih intro ganteng banget ngalah ngalahin boy group aespa drama intro aespadrama drama aespa
7339,"#URGENT #AlQassam siarkan rekaman: * Operasi di Beit Lid di Tepi Barat, 2 Nov 2023, yang sebabkan matinya 2 serdadu * Operasi memancing Zionis ke sebuah jebakan Abang-abang. Sampai skrg belum ada ...",,urgent alqassam siarkan rekaman operasi di beit lid di tepi barat 2 nov 2023 yang sebabkan matinya 2 serdadu operasi memancing zionis ke sebuah jebakan abang abang sampai sekarang belum ada pengum...,[Jewish],urgent alqassam siar rekam operasi beit lid tepi barat 2 nov 2023 sebab mati 2 serdadu operasi pancing zionis buah jebak abang abang sekarang umum resmi zionis berapa serdadu mati jebak vid
3691,Cuma berharap merka semua budek 😭,😭,cuma berharap merka semua budek,[Disabilitas],cuma harap merka semua budek
2553,"fenly yg ngelive, gw yg kayak orgil nyautin omongannya, berasa ngobrol 🙂 wkwk",🙂,fenly yang ngelive saya yang kayak orgil nyautin omongannya berasa ngobrol tertawa,[Disabilitas],fenly ngelive kayak orgil nyautin omong asa ngobrol tertawa
14726,"Katanya dikuasai CINA...😂😂 ""Warga Luwu Protes Perusahaan Smelter Rampas Lahan Petani, JK: Kami Sudah Beli"" Ternyata JK lagi 😛😛",😂 😂 😛 😛,katanya dikuasai cina warga luwu protes perusahaan smelter rampas lahan petani jk kami sudah beli ternyata jk lagi,[Tionghoa],kata asai cina warga luwu protes usaha smelter rampas lahan tani jk beli nyata jk
146,"Afa Mania, Angka yang naik untuk pasaran China hari ini adalah : Result : 2671 Shio : ULAR SAH - Selamat kepada pemenang !!! #Afapoker #togelterpercaya #Cerahkali",,afa mania angka yang naik untuk pasaran china hari ini adalah result 2671 shio ular sah selamat kepada pemenang afapoker togelterpercaya cerahkali,[Tionghoa],afa mania angka naik pasar china hari result 2671 shio ular sah selamat menang afapoker togelterpercaya cerahkali
38850,Operator Produksi Kualifikasi: Pria & Wanita. •Belum Menikah. •Umur max. ING) f bkksmkn3kotabekasi BUKA LOKER\n\nPT. Yamaha Music Manufacturing Asia\n\n#info #infojakarta #infobekasi #infoloker #...,,operator produksi kualifikasi pria wanita belum menikah umur max ing f bkksmkn3kotabekasi buka loker pt yamaha music manufacturing asia info infojakarta infobekasi infoloker smk lokersmk lokersma ...,[UNKNOWN],operator produksi kualifikasi pria wanita meni umur max ing f bkksmkn3kotabekasi buka loker pt yamaha music manufacturing asia info infojakarta infobekasi infoloker smk lokersmk lokersma lowongank...
17666,Hamas Makin Kuat! Pasukan Al Houthi dari Yaman Bantu Lawan Tentara Israel: Punya Rudal Jarak Jauh! VP: Erric SURYA.CO.ID - Pasukan Al Houthi dari Yaman telah menyatakan dukungannya pada Palestina ...,,hamas makin kuat pasukan al houthi dari yaman bantu lawan tentara israel punya rudal jarak jauh vp erric surya co id pasukan al houthi dari yaman telah menyatakan dukungannya pada palestina untuk ...,[Jewish],hamas makin kuat pasu al houthi yaman bantu lawan tentara israel punya rudal jarak jauh vp erric surya co id pasu al houthi yaman nyata dukung palestina lawan israel pasu milik nama resmi anshar a...
4351,Gais adakah rekomendasi sepatu bola lokalan yang bagus? Ponakanku lagi gila sepakbola sepatu sekolahnya dipake maen sampe jebol 😤. Help meeeee @rendraTEUB @arievrahman,😤,gais adakah rekomendasi sepatu bola lokalan yang bagus ponakanku lagi gila sepakbola sepatu sekolahnya dipake maen sampe jebol help me,[Disabilitas],gais ada rekomendasi sepatu bola lokal bagus ponakan gila sepakbola sepatu sekolah dipake maen sampe jebol help me
1262,"Belum Terjamah Manusia, Pantai Gayasan Blitar Jadi Saksi Bisu Hilangnya 8 ABK KM Mandala. 👇 Gayasan merupakan nama sebuah pantai yang berada di perbatasan antara Desa Kali Grenjeng, Kecamatan… #Pe...",👇,belum terjamah manusia pantai gayasan blitar jadi saksi bisu hilangnya 8 abk kamu mandala gayasan merupakan nama sebuah pantai yang berada di perbatasan antara desa kali grenjeng kecamatan peristi...,[Disabilitas],jamah manusia pantai gayasan blitar jadi saksi bisu hilang 8 abk kamu mandala gayasan rupa nama buah pantai ada batas desa kali grenjeng camat peristiwa blitar kabupatentrenggalek via

In [31]:
df.to_csv("../data/processed/data_cleaned_before_encode.csv")